### ISSUE TITLE
Coverage CMake

### ISSUE THREAD

**Issue by mkstoyanov** [ornl-training/basic-rse#5]
Currently the project specifies `cmake_minimum_required(VERSION 3.9)`, but the coverage module uses `find_package(Python)` which is a feature from 3.12. Older versions use `find_package(PythonInterp)`

We have to fix that in three ways:
* bump the cmake required version to something aggressive, e.g., 3.12 (from July 2018)
* be lazy and just document that GCOV requires a newer cmake
* switch to the older `find_package(PythonInterp)` module

**Comment by williamfgc** [comment]
@mkstoyanov I'd pick option 1) since the focus of the rse-training is also to move to "modern" cmake. What do you think?

**Comment by mkstoyanov** [comment]
@williamfgc That's OK, we can make them download and install CMake, just so they know how easy it is. It is very frustrating to see people that simply refuse to update to newer CMake, when it is one of the easiest things to do.
